stages:
  - secret_detection
  - test
  - build
  - release
  
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

secret_detection:
  stage: secret_detection
  variables:
    SECRETS_ANALYZER_VERSION: "5"
  rules:
    - if: $CI_COMMIT_TAG != ""
  before_script:
    - apk add --no-cache jq
  script:
    - /analyzer run
    - |
      if [ "$(jq ".vulnerabilities | length" gl-secret-detection-report.json)" -gt 0 ]; then
        echo "terdapat $(jq ".vulnerabilities | length" gl-secret-detection-report.json) leaks yang harus dibenahi"
        echo $(jq ".vulnerabilities" gl-secret-detection-report.json)
        exit 1
      else
        echo "tidak ada leaks ditemukan"
      fi
  allow_failure: false

test:
  image: registry.hub.docker.com/library/node:lts-alpine
  stage: test
  script:
    - npm install --silent
    - npm run test
    - npm run coverage
    - rm -f sonar-project.properties
    # - sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT -Dsonar.sources=bin -Dsonar.host.url=$SONAR_IP  -Dsonar.login=$SONAR_LOGIN -Dsonar.tests=test -Dsonar.language=js -Dsonar.source=bin -Dsonar.inclusions=**/*.js -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info -Dsonar.exclusions=coverage/**,**/*.html,**/*.css,bin/app/**,bin/deploy/**,test/** || true

  #dependencies:
  #  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --no-push
  dependencies:
    - test

release:
  stage: release
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker push $DOCKERHUB_USERNAME/$IMAGE_NAME
  dependencies:
    - build
  # only :
  #   - deploy

# deploy:
#   stage: deploy
#   tags:
#     - myihx2
#   script:
#     - oc login $OPENSHIFT --token=$TOKEN --insecure-skip-tls-verify
#     - oc project myihx
#     - oc rollout latest dc/$SERVICE
#   dependencies:
#     - release
